mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^trivia/', include('trivia.urls', namespace="trivia")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/trivia/urls.py
from django.conf.urls import patterns, url

from trivia import views


urlpatterns = patterns('',
    url(r'^daily/$', views.dailyview, name='daily'),
    url(r'^leader/$', views.leaderview.as_view(), name='leader'),
    url(r'^(?P<userid>\d+)/$', views.profileview, name='profile'),
    url(r'^correctResults/$', views.correctResultsView, name= 'results'),
    url(r'^incorrectResults/$', views.incorrectResultsView, name= 'results'),
    url(r'^$', views.user_login, name='login'),
    url(r'^signup/$', views.register, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^about/$', views.about_view, name='about'),
#    url(r'^/login/$', view.LoginView.as_view(), name='login')
#    url(r'^(?P<pk>\d+)/$', views.AnswerView.as_view(), name='answer'),
#    url(r'^(?P<pk>\d+)/leader/$', views.LeaderView.as_view(), name='leader'),
#    url(r'^(?P<question_id>\d+)/report/$', views.ReportView.as_view(), name='report'),
)

mysite/trivia/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
	date_open = models.DateField(primary_key=True)
	question_text = models.CharField(max_length=200)
	answer_text = models.CharField(max_length=200)
	
	def is_open(self):
		return self.date_open == timezone.now().date()

	def __str__(self):              # __unicode__ on Python 2
		return self.question_text

class MyUser(models.Model):
	user = models.OneToOneField(User, primary_key=True)
	num_correct = models.IntegerField(default=0)
	num_total = models.IntegerField(default=0)
	last_answered = models.DateField(null=True)

mysite/trivia/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, render_to_response, redirect
from django.views import generic
from trivia.models import Question, MyUser
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.contrib.auth.models import User

# Create your views here.

#You have to pass all variables in your view to the template using
#the dictionary in the render call. 

class AnswerForm(forms.Form):
	answer = forms.CharField(label = 'answer ', max_length = 150)

def dailyview(request):
	if not request.user.is_authenticated():
		return redirect('/trivia/')
	date = timezone.now().date()
	q = get_object_or_404(Question, pk=date)
	q_text = q.question_text
	userid = request.user.id
	user = get_object_or_404(MyUser, pk=request.user)

	if request.method == 'POST':
		form = AnswerForm(request.POST)
		if form.is_valid():
			user.last_answered = date
			answer_given = request.POST['answer']
			if answer_given == q.answer_text:
				user.num_correct += 1
				user.num_total = user.num_total + 1
				user.save()
				return HttpResponseRedirect('/trivia/correctResults/')
			else:
				user.num_total = user.num_total + 1
				user.save()
				return HttpResponseRedirect('/trivia/incorrectResults/')
		else:
			form = AnswerForm()
	else:
		form = AnswerForm()
	return render(request, 'dailyquestion.html', {'date': date, 'question_text': q_text, 'form': form, 'user': user})

def correctResultsView(request):
	userid = request.user.id
	user = get_object_or_404(MyUser, pk=userid)
	date = timezone.now().date()
	q = get_object_or_404(Question, pk=date)

	return render(request, 'correctResults.html', {'user': user, 'question': q})

def incorrectResultsView(request):
	userid = request.user.id
	user = get_object_or_404(MyUser, pk=userid)
	date = timezone.now().date()
	q = get_object_or_404(Question, pk=date)

	return render(request, 'incorrectResults.html', {'user': user, 'question': q})

class leaderview(generic.ListView):
	model = MyUser
	template_name = "leaderboard.html"
	context_object_name = 'user_list'
	#user = request.user

	def get_queryset(self):
		"""Return the last five published questions."""
		return MyUser.objects.order_by('-num_correct')

def profileview(request, userid):
	template_name = "profile.html"
	context_object_name = 'user'
	user = get_object_or_404(MyUser, pk=userid)
	return render(request, 'profile.html', {'user': user})

def user_login(request):
	context = RequestContext(request)

	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/trivia/daily/')
			else:
				return HttpResponse("Your account does not exist. Please sign up")
		else:
			print "Invalid login details: {0}, {1}".format(username, password)
			return HttpResponse("Invalid login details supplied")
	else:
		return render_to_response('login.html', {}, context)

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

def register(request):
	context = RequestContext(request)

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data=request.POST)

		if user_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			my_user = MyUser(user=user)
			my_user.save()
			registered = True
		else:
			print user_form.errors
	else:
		user_form = UserForm()

	return render_to_response('signup.html', {'user_form': user_form, 'registered': registered}, context)

def logout_view(request):
	logout(request)
	return redirect('/trivia/')

def about_view(request):
	return render(request, 'about.html', {})

mysite/trivia/templates/dailyquestion.html
<!DOCTYPE html>
<html>

{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'dailyquestionsheet.css' %}" />

<head>
   <title> Daily Question </title>
</head>

<body>
  <div>
   <table id="header">
     <tr>
      <th colspan="4"><h1>Miner Village Trivia Challenge</h1></th>
     </tr>
     <tr>
       <td><a href="{% url 'trivia:about' %}">About Us</a></td>
       <td><a href="{% url 'trivia:profile' user.user.id %}">Your Profile</a></td>
       <td><a href="{% url 'trivia:leader' %}">Leaderboard</a></td>
       <td><a href="{% url 'trivia:logout' %}">Logout</a></td>
     </tr>
   </table></div>
   <h2> Question for {{ date }} </h2>
   
   {% if not user.last_answered == date %}
      <h3> {{ question_text }} </h3>

      <form action="/trivia/daily/" method="POST">
      {% csrf_token %}
      {{ form }}
      <br><br>
      <input type="submit" value="Submit" />
      </form>
    
   {% else %}
      <h3> You have already answered the Question for today. </h3>
      <h3> Come back tomorrow! </h3>
   {% endif %}
   <br>
   <p>
      Check the <a href="{% url 'trivia:leader' %}">Leaderboard</a>
   </p>
</body>

</head>
</html>

mysite/trivia/templates/leaderboard.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'leaderboardsheet.css' %}" />
<head>
   <title> Leaderboard </title>
</head>

<body>
  <div>
   <table id="header">
     <tr>
      <th colspan="4"><h1>Miner Village Trivia Challenge</h1></th>
     </tr>
     <tr>
       <td><a href="{% url 'trivia:about' %}">About Us</a></td>
       <td><a href="{% url 'trivia:profile' user.id %}">Your Profile</a></td>
       <td><a href="{% url 'trivia:daily' %}">Daily Question</a></td>
       <td><a href="{% url 'trivia:logout' %}">Logout</a></td>
     </tr>
   </table></div>
   <h2> Leaderboard </h2>
   
   <table id="board" align="left" style="width:100%">
     <tr>
        <th align="center">Username</th>
        <th align="center">Total Points</th>
     </tr>

 <!--  for every user in database, display their user name and points in descending order  -->
   
   {% for x in user_list %}
     <tr>
        <td><a href = "{% url 'trivia:profile' x.user.id %}"> {{ x.user.username }}</a></td>
        <td>{{ x.num_correct }}</td>
     </tr>
   {% endfor %}
   </table>
</body>

</head>
</html>

mysite/trivia/templates/login.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'loginsheet.css' %}" />

<head>
   <title> Login </title>
</head>

<body>
  <div>
   <table id="header">
     <tr>
      <th><h1>Miner Village Trivia Challenge</h1></th>
     </tr>
     <tr>
       <td><a href="{% url 'trivia:about' %}">About Us</a></td>
    </tr>
  </table></div>
   <h2> Login </h2>
   
   <form id="login_form" method="post" action="/trivia/">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br/><br/>
    Password: <input type="password" name="password" value="" size="50" />
    <br/><br/>

    <input type="submit" value="submit" />
   </form>

   <br>
   <p>
      Don't have a username? <a href="{% url 'trivia:signup' %}">Sign Up</a>
   </p>

</head>
</html>

mysite/trivia/templates/profile.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'profilesheet.css' %}"/>
<head>
   <title> Profile </title>
</head>

<body>
  <div>
   <table id="header">
     <tr>
      <th colspan="4"><h1>Miner Village Trivia Challenge</h1></th>
     </tr>
     <tr>
       <td><a href="{% url 'trivia:about' %}">About Us</a></td>
       <td><a href="{% url 'trivia:daily' %}">Daily Question</a></td>
       <td><a href="{% url 'trivia:leader' %}">Leaderboard</a></td>
       <td><a href="{% url 'trivia:logout' %}">Logout</a></td>
     </tr>
   </table></div>
   <h2> Profile </h2>
   
   <table align="center">
     <tr>
        <td><strong>Username: </strong></td>
        <td/><td/>
        <td>{{ user.user.username }}</td><!-- make current username = username and display here -->
     </tr>
     <tr>
        <td><strong>Questions answered:</strong></td>
        <td/><td/>
        <td>{{ user.num_total }}</td><!-- query db and display number of questions answered -->
     </tr>
     <tr>
        <td><strong>Total correct:</strong></td>
        <td/><td/>
        <td>{{ user.num_correct }}</td><!-- query db for total points. Display-->
     </tr>
   </table>
   
</body>

</head>
</html>

mysite/trivia/templates/results.html
<!DOCTYPE html>
<html>
<link type="text/css" rel="stylesheet" href="resultssheet.css"/>
<head>
   <title> Results </title>
</head>

<body>
   <div id="header"><h1>Miner Village Trivia Challenge</h1></div>
   <h2> Results </h2>
   
   <table align="center">
     <tr>
        <td><strong>Your answer: </strong></td>
        <td/><td/>
        <td>[scheul93]</td><!-- make current username = username and display here -->
     </tr>
     <tr>
        <td><strong>Correct answer:</strong></td>
        <td/><td/>
        <td>[1]</td><!-- query db and display number of questions answered -->
     </tr>
     <tr>
        <td><strong>Points earned:</strong></td>
        <td/><td/>
        <td>[1]</td><!-- query db for total points. Display-->
     </tr>
     <tr>
       <td><strong>Total points:</strong></td>
       <td/><td/>
     </tr>
   </table>
   
   <p>
     <a href="mailto:acs2q3@mst.edu?Subject=Trivia Problem&body= My user name is ... and my problem is...">
     Report a problem</a>
     <br>
     (Please include your username and issue.)
   </p>
</body>

</head>
</html>

mysite/trivia/templates/signup.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'signupsheet.css' %}" />
<head>
   <title> Sign Up </title>
</head>

<body>
  <div>
   <table id="header">
     <tr>
      <th ><h1>Miner Village Trivia Challenge</h1></th>
     </tr>
     <tr>
       <td><a href="{% url 'trivia:about' %}">About Us</a></td>
    </tr>
  </table></div>
   <h2>


   {% if registered %}
   <br/>Thank you for registering!
   <a href='{% url 'trivia:daily' %}'> Go to daily question </a>
  
   {% else %}
   <br/>Register here!

   </h2>
   
   <form aid="user_form" method="post" action='/trivia/signup/'>
    {% csrf_token %}
    {{ user_form.as_p }}
    <br><br>
    <input type="submit" name="submit" value="Submit" />
   </form>

   {% endif %}
   <br>
</body>

</head>
</html>